"""Initial migration

Revision ID: 05ae9c6283c0
Revises: 
Create Date: 2025-04-09 13:06:25.390756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ae9c6283c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_order_id', sa.Integer(), nullable=True))
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'meal_order', ['meal_order_id'], ['id'])

    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_column('specialization')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('meal_order_id')

    # ### end Alembic commands ###
